"""empty message

Revision ID: 01f575a89c15
Revises: 9177dde00348
Create Date: 2016-10-29 20:15:24.667577

"""

# revision identifiers, used by Alembic.
revision = '01f575a89c15'
down_revision = '9177dde00348'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    ### end Alembic commands ###
