"""empty message

Revision ID: 8f26b31c47b4
Revises: None
Create Date: 2016-10-28 19:43:06.199511

"""

# revision identifiers, used by Alembic.
revision = '8f26b31c47b4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=55), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('encrypted_password', sa.Text(), nullable=True),
    sa.Column('auth_token', sa.Text(), nullable=True),
    sa.Column('auth_expires_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
