"""empty message

Revision ID: 9177dde00348
Revises: 8f26b31c47b4
Create Date: 2016-10-29 19:14:07.000977

"""

# revision identifiers, used by Alembic.
revision = '9177dde00348'
down_revision = '8f26b31c47b4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auth_token')
    op.drop_column('users', 'auth_expires_at')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_expires_at', sa.DATE(), nullable=True))
    op.add_column('users', sa.Column('auth_token', sa.TEXT(), nullable=True))
    ### end Alembic commands ###
